

# Site settings
title: "Watch.Games - Sport, Streaming & News"
email: "contact.watch.games@gmail.com"
baseurl: "watch_games" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/images/header-brand.webp
description: ""
keywords: "jekyll, minimal jekyll, jekyll theme, responsive jekyll, seo friendly blog, super fast blog, responsive"
mailclimp: ""
facebook: https://www.facebook.com/people/Watch-Games/61558637614285/
instagram: https://www.instagram.com/watch.games.official/
twitter: https://twitter.com/watchgames_real
pinterest: https://www.pinterest.com/watchgamesofficial/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-timeago


# Site configuration for the Jekyll 2 Pagination Gem
pagination:
  enabled: true
  debug: true
  collection: "posts"
  per_page: 8
  permalink: "/pages/:num/" # Pages are simple html files
  title: ":title - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  category: "posts"
  tag: ""
  locale: ""
  trail:
    before: 2
    after:
  extension: "html"
  indexpage: "index"

autopages:
  enabled: true
  categories:
    layouts: ["category.html"]
    title: ":cat"
    permalink: "/:cat"

  collections:
    layouts:
      - "category.html"
    title: " :coll"  # :coll is replaced by the collection name
    permalink: "/:coll/"

  tags:
    layouts:
      - "tag.html"
    title: ":tag" # :tag is replaced by the tag name
    permalink: "/tag/:tag"

tag_page_layout: category
tag_page_dir: tag
tag_permalink_style: pretty


collections:
  posts:
    output: true
    permalink: "/:categories/:title/"
  authors:
    output: true
    permalink: "/author/:path/"

feed:
  collections:
    posts:
      path: "/index.xml"
